### ISSUE TITLE
Which gen.py should I run?

### ISSUE THREAD

**Issue by Oliver-Q** [JarveeLee/SynthText_Chinese_version#1]
Hi, there. You've done really great work! Still there are several gen.py-like python files in the root dic. May I ask which one can generate Chinese text in my own picture? It's gen.py or generateDataNew.py or gen_cartoon.py and what's the function of them separately? Would you help me find this out？Any reply is genuinely appreciated.

**Comment by JarveeLee** [comment]
Sorry...You can see the readme updated just now.....

**Comment by Oliver-Q** [comment]
Thanks! And FYI just to mention, add # -*- coding: utf-8 -*- to corresponding files may be helpful.

**Comment by gydlcc** [comment]
you got the chinese character？！

**Comment by Oliver-Q** [comment]
![2](https://user-images.githubusercontent.com/15169060/27846074-3d762138-6167-11e7-998f-8661c0e54795.png)
Yeah, after deleting the missing fonts(does not exist in more_font folder) in fontlist.txt and deleting the hidden file(shown blow) in newsgroup folder which may lead to decoding error. Other parts work actually good now.
![image](https://user-images.githubusercontent.com/15169060/27846136-be183e84-6167-11e7-9bd2-b913d5feeac2.png)

**Comment by Oliver-Q** [comment]
An overview has been provided at:
https://oliver-q.github.io/Posts/Caffe/SynthText%20of%20Mandarin%20Chinese.html
