### ISSUE TITLE
How to speed up the generation of new images？

### ISSUE THREAD

**Issue by ljd16** [JarveeLee/SynthText_Chinese_version#11]
When generating texts in images, it takes severals second for each image and there are several warinings of "Times Out".
so is there any advice?

>  ** instance # : 0
> sample_output sample_para_output None
> []
> sample_para_output None
> before the if judge []
>  didn't pass because of len(text)==0
> sample_output    *** Timed out!
> sample_output sample_para_output None
> []
>    *** Timed out!

**Comment by FrBernkastel** [comment]
@ljd16 I have reviewed the code. Because there is strong possibility that the text_sample cannot get proper text for the certain region, the code sest a time out exception for endless loop. I cannot find way to speed up the generation, and I use multiprocessing to help me generate more pictures.

**Comment by ljd16** [comment]
@FrBernkastel 15 hours past, only 500 images were processed. If there are no more advices, I should accep your opinon.

**Comment by JarveeLee** [comment]
# @ljd16 I suffer from the same problem when generating char on complex natural images....May be you can change the code by doing so: Firstly choose the largest stable region and then choose acceptable length of sentence , this code is doing the opposite so to be slow like this....

**Comment by ljd16** [comment]
@JarveeLee Thank you, I will try later. Recently, I have found a new dataset [RCTW-17](http://mclab.eic.hust.edu.cn/icdar2017chinese/dataset.html) which contains Chinese Text in the Wild(12,034 images, 8034 images for training and 4000 images for testing)

**Comment by binzhang** [comment]
How about the generateDataNew.py?  It is super fast, but the img it generated is not quite the same as the gen.py, it seems more faked.

**Comment by xiiiiiiii** [comment]
> Thank you, I will try later. Recently, I have found a new dataset [RCTW-17](http://mclab.eic.hust.edu.cn/icdar2017chinese/dataset.html) which contains Chinese Text in the Wild(12,034 images, 8034 images for training and 4000 images for testing)

你好，想问一下你在 RCTW-17 数据集上的效果如何？准确率和召回率还有f1如何呢？
