### ISSUE TITLE
Issue when calling python gen.py --viz

### ISSUE THREAD

**Issue by lisayan** [JarveeLee/SynthText_Chinese_version#12]
Here's some example output

1 of 4
 ** instance # : 0
sample_output sample_para_output None
[]
sample_para_output [u'\uff33\u732a\u2462']
before the if judge Ｓ猪③
pass the text filter
pass in mask array size
text in synthgen.py/place_text to return Ｓ猪③
text in synthgen.py/render_text append into itext Ｓ猪③
sample_output sample_para_output None
[]
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output sample_para_output None
[]
sample_para_output [u'\u5feb\u5feb\u53d7\u6b7b\u5427\uff01\u201d', u'\u7eed\u4e86\u597d\u591a\u5929\u3002']
before the if judge 快快受死吧！”
续了好多天。
pass the text filter
pass in mask array size
sample_output sample_para_output [u'\u6240\u4ee5\u5b83\u5c31\u5f97\u5230\u4e86\u516c\u4e3b\u3002', u'\u201c\u518d\u4f1a\uff0c\u201d\u516c\u4e3b\u56de\u7b54\u8bf4\u3002']
所以它就得到了公主。
“再会，”公主回答说。
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output sample_para_output None
[]
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output sample_para_output [u'\u886c\u886b\u9886\u5b50', u'\u8e2a\u4e86\u3002\u201d']
衬衫领子
踪了。”
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output sample_para_output [u'&\u4e0b&\u4e66_']
&下&书_
sample_para_output [u'\u4e86\u3002']
before the if judge 了。
pass the text filter
pass in mask array size
text in synthgen.py/place_text to return 了。
text in synthgen.py/render_text append into itext 了。
sample_output    *** Timed out!
sample_output    *** Timed out!
sample_output sample_para_output None
[]
sample_para_output [u'\u6728\u9e21\u517b\u9053']
before the if judge 木鸡养道
pass the text filter
pass in mask array size
text in synthgen.py/place_text to return 木鸡养道
text in synthgen.py/render_text append into itext 木鸡养道
sample_output sample_para_output None
[]
   *** Timed out!
sample_output sample_para_output [u'\u5b89\u7136\u7761\u5230\u5929\u660e\u3002']
安然睡到天明。
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output    *** Timed out!
sample_output sample_para_output None
[]
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output    *** Timed out!
sample_output sample_para_output None
[]
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output    *** Timed out!
sample_output sample_para_output [u'\u52a8\u5730\u8bf4\uff1a']
动地说：
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output    *** Timed out!
sample_output sample_para_output [u'\u4f60\u4eec\u3002\u201d']
你们。”
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output    *** Timed out!
sample_output sample_para_output None
[]
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output    *** Timed out!
sample_output    *** Timed out!
sample_output sample_para_output [u'\u70e6\u607c\u3002']
烦恼。
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
sample_output sample_para_output [u'\u3000\u3000\u5bf9\u4e86\u3002']
对了。
sample_para_output [u'\u4e0b{ \u4e66']
before the if judge 下{ 书
pass the text filter
pass in mask array size
text in synthgen.py/place_text to return 下{ 书
text in synthgen.py/render_text append into itext 下{ 书
sample_output    *** Timed out!
[u'\uff33\u732a\u2462', u'\u4e86\u3002', u'\u6728\u9e21\u517b\u9053', u'\u4e0b{ \u4e66']
Traceback (most recent call last):
  File "gen.py", line 192, in main
    ninstance=INSTANCE_PER_IMAGE,viz=viz)
  File "/home/pothole/text_recognition/SynthText_Chinese_version/synthgen.py", line 693, in render_text
    viz_textbb(1,img, [idict['wordBB']], alpha=1.0)
  File "/home/pothole/text_recognition/SynthText_Chinese_version/synthgen.py", line 351, in viz_textbb
    plt.figure(fignum)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable
>>>> CONTINUING....
depth shape,img shape (446, 600, 2) (743, 1000, 3)
depth info [[[  2.28360033  81.91452789]
  [  2.28360033  81.91452789]
  [  2.28360033  81.91451263]
  ...,
  [  2.09834814  81.91157532]
  [  2.09834814  81.91158295]
  [  2.09834814  81.91158295]]

 [[  2.28360033  81.91453552]
  [  2.28360033  81.91452789]
  [  2.28360033  81.91452026]
  ...,
  [  2.09834814  81.91158295]
  [  2.09834814  81.91158295]
  [  2.09834814  81.91159058]]

 [[  2.28360033  81.91454315]
  [  2.28360033  81.91454315]
  [  2.28360033  81.91453552]
  ...,
  [  2.09834814  81.91159821]
  [  2.09834814  81.91159058]
  [  2.09834814  81.91159058]]

 ...,
 [[  1.34355438   6.31256342]
  [  1.34355438   6.31259346]
  [  1.34355438   6.31277084]
  ...,
  [  1.44243908   5.58638668]
  [  1.44243908   5.58641577]
  [  1.44243908   5.5864315 ]]

 [[  1.34355438   6.3125391 ]
  [  1.34355438   6.31220341]
  [  1.34355438   6.31213331]
  ...,
  [  1.44243908   5.58516884]
  [  1.44243908   5.58522034]
  [  1.44243908   5.58521461]]

 [[  1.34355438   6.31251287]
  [  1.34355438   6.31235409]
  [  1.34355438   6.3122406 ]
  ...,
  [  1.44243908   5.58518744]
  [  1.44243908   5.58520794]
  [  1.44243908   5.58521891]]]
depth max min 81.9185 0.7133
hsv_img_shape (446, 600, 3)
H_channel (600, 446) [[ 255.  255.  255. ...,  230.  236.  234.]
 [ 255.  255.  255. ...,  233.  234.  235.]
 [ 255.  255.  255. ...,  232.  235.  234.]
 ...,
 [ 255.  255.  255. ...,  251.  253.  251.]
 [ 255.  255.  255. ...,  253.  253.  251.]
 [ 255.  255.  255. ...,  252.  252.  250.]]
H_max min 255.0 11.0
scale 0.321249
depth shape (446, 600, 2)
depth max min 81.9185 0.7133
seg info (479, 647) (198,) (198,)

**Comment by JarveeLee** [comment]
What is your problem..?

**Comment by lisayan** [comment]
I'm not sure if this gen.py is working correctly since when I call python visualize_results.py I get an error. Is this output normal?

**Comment by JarveeLee** [comment]
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in init
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable

You didn't install something necessary for displaying images....Does your cv2.imshow() work?

**Comment by lisayan** [comment]
Oh ok, I fixed this error by ssh-ing with the -X flag. I have another issue though. Do you have an idea of where to start? This is what I get after calling python gen.py --viz.

  File "gen.py", line 223, in <module>
    main(args.viz)
  File "gen.py", line 130, in main
    RV3 = RendererV3(DATA_PATH,max_time=SECS_PER_IMG)
  File "/home/pothole/text_recognition/SynthText_Chinese_version/synthgen.py", line 369, in __init__
    self.text_renderer = tu.RenderFont(data_dir)
  File "/home/pothole/text_recognition/SynthText_Chinese_version/text_utils.py", line 111, in __init__
    fn=osp.join(data_dir,'newsgroup/'))
  File "/home/pothole/text_recognition/SynthText_Chinese_version/text_utils.py", line 546, in __init__
    line=line.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 45: invalid start byte

**Comment by JarveeLee** [comment]
It means your OS fails to read chinese filename in newsgroup/.....you should install something for OS as well

**Comment by lisayan** [comment]
Thanks for your quick response! After I did that and called python gen.py --viz, I got images to show up but they had boxes instead of Chinese characters. I was reading the other issues and they said they had something similar but they said that they were creating a new font, while I am only trying to use existing ones. I tried adding one of the fonts under more_font into fontlist.txt, but it still doesn't seem to work. Do you have any suggestions?

**Comment by JarveeLee** [comment]
Create your font_px2pt.cp by editting font_list.txt(adding preferred font's name ) and then run invert_font_size.py ...After long time as well I forget which font is contained in uploaded font_px2pt.cp ....

**Comment by lisayan** [comment]
Hmm, it still doesn't seem to have characters, only boxes. When I print the files under newsgroup/ to test if my OS can read Chinese should it output Chinese characters? Right now it can print everything but for the Chinese names it comes out like \xe9\xa3\x8e\xe5\x8f\x88\xe4\xb8\x89\xe9\x83\x8e.txt

**Comment by JarveeLee** [comment]
It should print Chinese characters or their unicode..This isn't ...

**Comment by dyzhou2015** [comment]
@lisayan @JarveeLee  I has met the same problem, the images I generate have only bounding boxes instead of chinese characters.and I have put the new font_px2pt.cp into data/models directory. however it doesnot seem to work, any suggestions? thank you very much.It disturbs me days long.

**Comment by dyzhou2015** [comment]
ok, It worked, the problem is the font_px2pt.cp should not be ubuntu* font. How can I get more character font ?

**Comment by northeastsquare** [comment]
Yes, dyzhou2015, should delete the ubuntu font. Or , program will display chinese charactor with the ubuntu font.

**Comment by dajidali010** [comment]
@dyzhou2015 Have you solved your problem?  I generate have only bounding boxes instead of Chinese characters, too. thanks a lot

**Comment by CRonaldo1997** [comment]
Thanks for your project but do you have a python 3 version?

**Comment by LiuHuiyue666** [comment]
@lisayan I met the same problem,please can you tell me how to solve it ?I will appreciate it if you can response to me .Thanks!
File "gen.py", line 226, in <module>
    main(args.viz)
  File "gen.py", line 133, in main
    RV3 = RendererV3(DATA_PATH,max_time=SECS_PER_IMG)
  File "E:\mine\Qingroup\DetectionText\SynthText_Chinese_version-master\synthgen.py", line 373, in __init__
    self.text_renderer = tu.RenderFont(data_dir)
  File "E:\mine\Qingroup\DetectionText\SynthText_Chinese_version-master\text_utils.py", line 116, in __init__
    fn=osp.join(data_dir, 'newsgroup/'))
  File "E:\mine\Qingroup\DetectionText\SynthText_Chinese_version-master\text_utils.py", line 545, in __init__
    fc=filename.decode('utf-8')
  File "D:\python2.7.15\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 0: invalid start byte

**Comment by LiuHuiyue666** [comment]
@JarveeLee  Excuse me,my OS fails to read chinese filename in newsgroup/.What should I install to solve this problems?This problem takes me a few of days.Thank you very much!

**Comment by 1LOVESJohnny** [comment]
> @lisayan I met the same problem,please can you tell me how to solve it ?I will appreciate it if you can response to me .Thanks!
> File "gen.py", line 226, in
> main(args.viz)
> File "gen.py", line 133, in main
> RV3 = RendererV3(DATA_PATH,max_time=SECS_PER_IMG)
> File "E:\mine\Qingroup\DetectionText\SynthText_Chinese_version-master\synthgen.py", line 373, in **init**
> self.text_renderer = tu.RenderFont(data_dir)
> File "E:\mine\Qingroup\DetectionText\SynthText_Chinese_version-master\text_utils.py", line 116, in **init**
> fn=osp.join(data_dir, 'newsgroup/'))
> File "E:\mine\Qingroup\DetectionText\SynthText_Chinese_version-master\text_utils.py", line 545, in **init**
> fc=filename.decode('utf-8')
> File "D:\python2.7.15\lib\encodings\utf_8.py", line 16, in decode
> return codecs.utf_8_decode(input, errors, True)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 0: invalid start byte

Hi, have you solved the problem? I meet the same.
