### ISSUE TITLE
add new images to depth

### ISSUE THREAD

**Issue by songwendong** [JarveeLee/SynthText_Chinese_version#17]
Hello,
When I run the program, I encounter the following problems

![image](https://user-images.githubusercontent.com/16954370/31998892-f9e7f012-b9c3-11e7-9ce5-2da6b1f1f696.png)

Who encountered a similar problem, how to solve?
@JarveeLee 
Can predict_depth.m  be used directly?

**Comment by JarveeLee** [comment]
Ah I never met this problem before...I just run those matlab code....

**Comment by songwendong** [comment]
@JarveeLee   Will this matlab code can be used directly? needn't to change any thing . thanks.

**Comment by yingning** [comment]
@songwendong ，Ｈello ,have you solved your problem?Any help will be appreciated!
