### ISSUE TITLE
when I run    python gen.py --viz

### ISSUE THREAD

**Issue by ray0809** [JarveeLee/SynthText_Chinese_version#2]
It returns a error:
Traceback (most recent call last):
  File "gen.py", line 142, in main
    img_resize=img.resize(db['depth'][imname].shape)
  File "/home/ray/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 1529, in resize
    return self._new(self.im.resize(size, resample))
TypeError: argument 1 must be sequence of length 2, not 3

Would you help me to solve the problem

**Comment by safehumeng** [comment]
img_resize=img.resize(db['depth'][imname].shape[1:3])

**Comment by Oliver-Q** [comment]
img_resize=img.resize(db['depth'][imname][0,:,:].shape)
also feasible
