### ISSUE TITLE
JarveeLee

### ISSUE THREAD

**Issue by songwendong** [JarveeLee/SynthText_Chinese_version#20]
@JarveeLee  Thank you for your perfect job。When I run the program, the picture shows only a box, no words, what is the reason for this?  like this picture below:

![qq 20171030165953](https://user-images.githubusercontent.com/16954370/32162828-3d6a08be-bd95-11e7-86e5-00bb93f63678.jpg)

thank you

**Comment by JarveeLee** [comment]
Does this frequently happen..?Most of your generated images?

**Comment by songwendong** [comment]
@JarveeLee   thank you very much  to your teachings.
how to  adjust the size of the font? adjust the font to  thick and fine , like the following words, too thick,too big.
![qq 20171101141851](https://user-images.githubusercontent.com/16954370/32263307-51045b24-bf14-11e7-8ff6-f1b890c8b8e8.jpg)
