### ISSUE TITLE
several questions

### ISSUE THREAD

**Issue by dajidali010** [JarveeLee/SynthText_Chinese_version#21]
Hi, thanks a lot for your great job! 
I can use your code now, but when I run your code, an error still happened.
File "gen.py", line 143, in main
    img_resize=img.resize(db['depth'][imname].shape)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1745, in resize
    return self._new(self.im.resize(size, resample, box))
TypeError: must be sequence of length 2, not 3
So,I change a little,  img_resize=img.resize(db['depth'][imname].shape)     to 
img_resize=img.resize((db['depth'][imname].shape[1], db['depth'][imname].shape[2]))

More, after a long time, I only got few images. And "Timed out" occurred frequently. Why?
Could you give me some suggestions?
![1](https://user-images.githubusercontent.com/32895342/32368479-cb50b79e-c0c0-11e7-8ee5-a81c612fe7d7.png)
![2](https://user-images.githubusercontent.com/32895342/32368500-df16a518-c0c0-11e7-8f52-6f5065049756.png)

![3](https://user-images.githubusercontent.com/32895342/32368578-2032fbbe-c0c1-11e7-89d5-0687c47389ea.png)

**Comment by yingning** [comment]
Ｉ had the same error ,have you solved it? @dajidali010

**Comment by dupf** [comment]
yes i have the same error

**Comment by dupf** [comment]
why @dajidali010

**Comment by dajidali010** [comment]
i still want to why too......

**Comment by gangliu123** [comment]
It looks like I ran the code successfully, but I cannot find the picture. Could you guys tell me why, much appreciated.
![issue](https://user-images.githubusercontent.com/31200030/37140454-aa410946-22a9-11e8-9220-a50428334c2a.PNG)
