### ISSUE TITLE
cannot find the font

### ISSUE THREAD

**Issue by lanyuelvyun** [JarveeLee/SynthText_Chinese_version#3]
When I run the gen.py,  the following error occurred:

Traceback (most recent call last):
  File "/Users/humeng/Downloads/work/SynthText_Chinese_version/synthgen.py", line 665, in render_text
    regions['homography_inv'][ireg])
  File "/Users/humeng/Downloads/work/SynthText_Chinese_version/synthgen.py", line 502, in place_text
    render_res = self.text_renderer.render_sample(font,collision_mask)
  File "/Users/humeng/Downloads/work/SynthText_Chinese_version/text_utils.py", line 357, in render_sample
    f_h = self.font_state.get_font_size(font, f_h_px)
  File "/Users/humeng/Downloads/work/SynthText_Chinese_version/text_utils.py", line 477, in get_font_size
    m = self.font_model[font.name]
KeyError: 'FZXiHei I-Z08S'

And the same error occurred for the other Chinese fonts.

**Comment by JarveeLee** [comment]
Maybe your OS can not support unicode for chinese ?? I as well struggled for days on installing chinese support on Ubuntu before running these code.....

**Comment by lanyuelvyun** [comment]
Thank you. I found the reason. The problem is the path of the font_px2pt.cp. When I use the fontlist.txt （in SynthText_Chinese_version/data/fonts/）provided by the author, I  need to use invert_font_size.py to generate a new font_px2pt.cp，and this new font_px2pt.cp is placed in  the current folder（where the invert_font_size.py is located），so we need to change the path of font_px2pt.cp in text_utils.py.

**Comment by gydlcc** [comment]
so do you got picture which include chinese character？！

**Comment by lanyuelvyun** [comment]
yes, I got the picture with chinese character.

**Comment by gydlcc** [comment]
alright ，i will try it，and are you Chinese？！

**Comment by lanyuelvyun** [comment]
是

**Comment by dyzhou2015** [comment]
@lanyuelvyun 嗨，你好，成功产生中文图片了么，我也碰到这个问题，就是产生的图片只有空白包围框，然后我也已经把invert_font_size.py生成的 font_px2pt.cp 放到了data/models文件夹内，但是已经不work，有什么建议吗，谢谢啊？
