### ISSUE TITLE
Nothing in pictures

### ISSUE THREAD

**Issue by gydlcc** [JarveeLee/SynthText_Chinese_version#4]
hi ，i run the gen.py --viz. 
 but i got picture which only got some box not chars and no chinese，so，how to solve this problem

**Comment by lanyuelvyun** [comment]
Maybe is the problem of the font_px2pt.cp. Do you create a new font_px2pt.cp by using invert_font_size.py? After you create a new one, don not forget to modify the path of font_px2pt.cp in text_utils.py（font_px2pt.cp is used inside text_utils.py）.

**Comment by gydlcc** [comment]
so you got chinese character in the picture？！

**Comment by w5688414** [comment]
22.
   *** Timed out!
sample_output    *** Timed out!
sample_output    *** Timed out!
sample_output sample_para_output None
[]
sample_para_output None
before the if judge []
 didn't pass because of len(text)==0
the error occurred, and  I can not get chinese in the picture
