### ISSUE TITLE
合成样本时有些汉字生成不出来

### ISSUE THREAD

**Issue by pingzi5233** [JarveeLee/SynthText_Chinese_version#50]
您好，我在合成中文样本时，出现这样一个问题，就是有的汉字是合成不出来的，例如：“玥”
假如要合成的文本行是“宇文玥宇文玥”，生成的图像里会发现“玥”这个汉字是缺少的了，有的是直接跳过生成这个汉字了，变成“宇文宇文”，有的是会出现空格，变成“宇文 宇文 ”，请问您知道这是什么问题吗？
非常感谢！

**Comment by 1LOVESJohnny** [comment]
您好，请问最后是怎么处理的？

**Comment by pingzi5233** [comment]
我这好像是字体文件的问题，.tff文件，有些字体文件包含的字符个数是一定的，供参考



神玥互联网-科技研究院 王萍
联系电话：13672218501
电子邮箱：wangping@atwasoft.net
 
发件人： 1LOVESJohnny
发送时间： 2019-06-28 15:33
收件人： JarveeLee/SynthText_Chinese_version
抄送： pingzi5233; State change
主题： Re: [JarveeLee/SynthText_Chinese_version] 合成样本时有些汉字生成不出来 (#50)
您好，请问最后是怎么处理的？
