### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 0

### ISSUE THREAD

**Issue by lanyuelvyun** [JarveeLee/SynthText_Chinese_version#6]
When I run gen.py on  Windows, this error occurs：UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 0。

Do you know how to solve it？

**Comment by Oliver-Q** [comment]
After deleting the missing fonts(does not exist in more_font folder) in fontlist.txt and deleting the hidden file(shown blow) in newsgroup folder which may lead to decoding error.
https://github.com/JarveeLee/SynthText_Chinese_version/issues/1

**Comment by lisayan** [comment]
I am getting this error too but it says 

UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 45: invalid start byte

I was able to delete the hidden file, but what missing fonts are you referring to? In my fontlist.txt, it doesn't refer to more_font folder at all.

**Comment by yingning** [comment]
@lisayan , Hello,I  got the same problem,have you fixed the bug?

**Comment by LiuHuiyue666** [comment]
@yingning Excuse me,I got the same problem,have you fixed the bug?I will appreciate it if you can response to me,Thanks!
