### ISSUE TITLE
未定义函数或变量 'read_img_rgb'。

### ISSUE THREAD

**Issue by w5688414** [JarveeLee/SynthText_Chinese_version#7]
can you provide the function for read_img_rgb, I got this error when I tried to run predict_depth.m
thanks a lot

**Comment by w5688414** [comment]
I have solved this problem by  searching the read_img_rgb.m file through google, but I got another error
I use malab2016 to run this program, the information is below
loading trained model...

1 of 1
 > super-pix
 > CNN
network forward for depth prediction...
尝试将 SCRIPT vl_nnconv 作为函数执行:
/home/idc/下载/dcnf-fcsp/libs/matconvnet_20141015/matlab/vl_nnconv.m

出错 my_nn_struct_forward (line 43)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride',
      l.stride) ;

出错 do_model_evaluate (line 23)
res = my_nn_struct_forward(net, img_data, [], ...

出错 predict_depth>get_depth (line 93)
    depth = do_model_evaluate(model, ds, opts);

出错 predict_depth (line 58)
        depth = get_depth(img,model.(imtype),opts);

**Comment by JarveeLee** [comment]
avoid path containing chinese char and my matlab is 2014..and to run those matlab code you need those relevant dependence provided by author to install.

**Comment by w5688414** [comment]
@JarveeLee  thanks a lot, the problem solved since I update my gcc verision into gcc 4.9, But I got another error since I run the add_more_data.py 
I don't know where the get_data() function is
the code is below:
 depth_db=get_data(more_depth_path)
  seg_db=get_data(more_seg_path)

and when I try to run the program, I got an additional error

`/usr/bin/python2.7 /home/idc/下载/SynthText_Chinese_version/add_more_data.py
Traceback (most recent call last):
  File "/home/idc/下载/SynthText_Chinese_version/add_more_data.py", line 49, in <module>
    add_more_data_into_dset(DB_FNAME,more_img_file_path,more_depth_path,more_seg_path)
  File "/home/idc/下载/SynthText_Chinese_version/add_more_data.py", line 15, in add_more_data_into_dset
    db=h5py.File(DB_FNAME,'wb+')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 128, in make_fid
    raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a")
ValueError: Invalid mode; must be one of r, r+, w, w-, x, a`
who can help me ?

**Comment by JarveeLee** [comment]
it is just a function opening HDF5 dataset....The same as  h5py.File(DB_FNAME,'r').....

**Comment by w5688414** [comment]
@JarveeLee  thanks a lot, I have solved my problem

**Comment by lyc6749** [comment]
> @JarveeLee thanks a lot, the problem solved since I update my gcc verision into gcc 4.9, But I got another error since I run the add_more_data.py
> I don't know where the get_data() function is
> the code is below:
> depth_db=get_data(more_depth_path)
> seg_db=get_data(more_seg_path)
> 
> and when I try to run the program, I got an additional error
> 
> `/usr/bin/python2.7 /home/idc/下载/SynthText_Chinese_version/add_more_data.py Traceback (most recent call last): File "/home/idc/下载/SynthText_Chinese_version/add_more_data.py", line 49, in <module> add_more_data_into_dset(DB_FNAME,more_img_file_path,more_depth_path,more_seg_path) File "/home/idc/下载/SynthText_Chinese_version/add_more_data.py", line 15, in add_more_data_into_dset db=h5py.File(DB_FNAME,'wb+') File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 271, in __init__ fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr) File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 128, in make_fid raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a") ValueError: Invalid mode; must be one of r, r+, w, w-, x, a`
> who can help me ?

how can you solve this problem？

**Comment by xiaohongxiao** [comment]
> > @JarveeLee thanks a lot, the problem solved since I update my gcc verision into gcc 4.9, But I got another error since I run the add_more_data.py
> > I don't know where the get_data() function is
> > the code is below:
> > depth_db=get_data(more_depth_path)
> > seg_db=get_data(more_seg_path)
> > and when I try to run the program, I got an additional error
> > `/usr/bin/python2.7 /home/idc/下载/SynthText_Chinese_version/add_more_data.py Traceback (most recent call last): File "/home/idc/下载/SynthText_Chinese_version/add_more_data.py", line 49, in <module> add_more_data_into_dset(DB_FNAME,more_img_file_path,more_depth_path,more_seg_path) File "/home/idc/下载/SynthText_Chinese_version/add_more_data.py", line 15, in add_more_data_into_dset db=h5py.File(DB_FNAME,'wb+') File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 271, in __init__ fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr) File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 128, in make_fid raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a") ValueError: Invalid mode; must be one of r, r+, w, w-, x, a`
> > who can help me ?
> 
> how can you solve this problem？

this answer is that you need to compile MatConvNet in order to generate the MEX. the address you can use:https://www.vlfeat.org/matconvnet/install/#compiling. use gcc4.9.4 also can compile to sucess.
