### ISSUE TITLE
Can't put chinese text in the picture

### ISSUE THREAD

**Issue by FrBernkastel** [JarveeLee/SynthText_Chinese_version#9]
After running the program, I fail to see any chinese texts except bounding_box in the picture. But when the program produced English words or paragraphs, everything is normal. I have read the source code and traced back to the text_utils.py , but have not figured out the problems. Maybe the problem about fonts. @JarveeLee

**Comment by JarveeLee** [comment]
How does your generated picture look like..........? @FrBernkastel

**Comment by FrBernkastel** [comment]
![sav_sandwich_96_0](https://user-images.githubusercontent.com/15198160/29200364-53897da2-7e87-11e7-8a97-10b4b716a4ce.jpg) It is the picture produced by English and it is normal.

![indian musicians_116](https://user-images.githubusercontent.com/15198160/29200430-c563b8d4-7e87-11e7-9b99-230ab9984033.jpg)
And it is the Chinese Version.

PS: whether should I copy the font_px2pt_2.cp and char_freq.cp into ./data/models? I have done it since I saw the ISSUE https://github.com/JarveeLee/SynthText_Chinese_version/issues/4

**Comment by JarveeLee** [comment]
1 invert_font_size.py 
2 the new font_px2pt_2.cp should be in data/models 
3 font_list.txt should be updated....
All done.....?

**Comment by FrBernkastel** [comment]
Oh, i never updated font_list.txt. I will have a try. Thanks anyway.
